### ISSUE TITLE
How to target currently active workspace

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-microsoft-vscode#3]
I normally have 2 VSCode workspaces open. I would like this module to be able to target whichever workspace is currently focussed/active. It currently only operates on one, I'm guessing the one I opened first.
I can't see anything in the documentation on this. Is it possible, please?

**Comment by pdiehm** [comment]
I guess "2 VSCode workspaces" also means 2 VSCode windows, right? In that case your guess is right: The first window opens up a WebSocket server on the specified port and the second window will quietly fail to bind the server to the same port. A workaround for that might be setting a different port for each workspace in the local configuration (in "${workspaceFolder}/.vscode/settings.json") and adding a Companion module instance for each workspace - this way you could at least control both windows, although sans focus detection.
Obviously the best fix would be to turn around the roles, making the Companion module the server and the VSCode plugin the client - I guess running multiple VSCode instances is more common than running multiple Companion instances. I might look into that in the future - no promises though.

**Comment by jgclark** [comment]
OK, thanks for commenting quickly.
Yes, I have 2 windows, one for each workspace.
Your first suggestion might be possible if I was always using the same 2 workspaces. But I have several that I'm generally working between, so this doesn't scale well.
Perhaps for now you could just add a note to the documentation to explain this limitation?

**Comment by pdiehm** [comment]
I guess I could add a note to the documentation, but I'm probably not going to do that as publishing (more precisely: bundling) a new version of the module always takes manual actions and some time and I plan on having this implemented by the end of the week.

**Comment by jgclark** [comment]
Thanks for the 2.0.0 update.  Apologies, but I can't see how to get it working. 

In VSCode I've set the following in User-level settings.json:
```
"commandsocket.newCryptoWarning": false,
"commandsocket.password": "<secret>",
"commandsocket.port": 6783,
"commandsocket.host": "127.0.0.1",
"commandsocket.role": "client", // to allow multiple instances to connect
```
And in Companion app setup is:
![Companion-module@2x](https://github.com/bitfocus/companion-module-microsoft-vscode/assets/1671754/ea23b16e-6a12-4bde-bb2c-f6536379326b)

I have restarted the module in Companion.

It is only showing the details of the first-opened workspace still. Please advise what steps I'm missing.

**Comment by pdiehm** [comment]
Yeah, unfortunately you'll have to wait until the module version 2.0.0 is released for companion (you are probably running version 1.1.0 right now, which still expects VSCode to run a server). I've asked for the release but sadly I don't have any more influence on the timing. Hopefully it will be contained in the next companion release, though.
If you can't wait you can also clone this repo into a local folder, run `yarn build` and add the parent folder as your module development folder in the companion setup window. You should then see module version 2.0.0 loaded in companion.
P.S.: It's funny that it still shows details about a single workspace. In theory you are trying to connect two clients and it shouldn't do anything right now... Maybe you didn't reload/restart VSCode? The automatic reloading mechanic doesn't really work at the moment...

**Comment by jgclark** [comment]
Understood, thanks. I can wait.
