### ISSUE TITLE
How to use 3 of the commands from Companion Module?

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-microsoft-vscode#4]
The table in https://marketplace.visualstudio.com/items?itemName=pascaldiehm.commandsocket shows 9 commands. I can see how the first 6 of them map to the commands that the Module offers in the UI:
![CleanShot 2024-02-09 at 17 44 06@2x](https://github.com/bitfocus/companion-module-microsoft-vscode/assets/1671754/ee302d77-69f8-4ec5-b9ee-ea74c7232ce1)
But I can't see how to issue the "get-* actions.
What am I missing, please?

**Comment by pdiehm** [comment]
The short version: You don't.
The long version: The three get-* commands are used to retrieve information about the editor. These are actually automatically called in the background (you can change the intervals in the instance config) and their result is provided in the instance variables.
(Please close this issue if that answers your question)

**Comment by jgclark** [comment]
Aha, thanks.  It's the first time I've used variables in Companion so I didn't think to look there.
Again, a quick note in the documentation wouldn't hurt.
Thanks.
