### ISSUE TITLE
Suggested example expression

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-microsoft-vscode#5]
I'm running Companion 3.3.0+6693 beta against module 1.1.0 and VSCode extension 2.0.0.

After a lot of fiddling I've now got the expression syntax right to replace resulting "%20" in the filename with spaces.
As the expression syntax doesn't contain many complete examples, I offer the following as a suggested note for your documentation:
`replaceAll(parseVariables('$(VSCode:status_editor_document_name)'),"%20"," ")`

**Comment by pdiehm** [comment]
Actually the %20 in there is and was a bug in the API. It does not happen with the new API and I fixed it in the legacy interface in version 2.0.1 for VSCode.
